### ISSUE TITLE
Add key allowing arbitrary metadata to be stored for tasks/repositories

### ISSUE THREAD

**Issue by Lukas-Dresel** [rhelmot/pydatatask#15]
E.g. for tasks we'd like to do things like 
```
maturity: fully_integrated
comment: "A component that does thing A and then thing B and does them well."
```

For repositories we might want to comment the semantic meaning of the contents similarly. 

This would allow these outputs to be included in visualizations, e.g. for single-component graphs we could include the comments of the data sources and sinks as well as the task itself to create an auto-documenting system.

**Comment by rhelmot** [comment]
![image](https://github.com/rhelmot/pydatatask/assets/2498805/ab31036b-24c6-4f6c-a683-6a0a09485ca5)

This is also technically supported for repositories, but it is inaccessible as we are currently using lockfiles to generate all repository constructors.

**Comment by Lukas-Dresel** [comment]
I've started annotating tasks and am using it to incorporate the maturity colors into the auto-generated graphs now.
