### ISSUE TITLE
Add task whitelisting to pd run to only allow certain tasks to be run for testing

### ISSUE THREAD

**Issue by Lukas-Dresel** [rhelmot/pydatatask#20]
E.g. If i want to test symcts in the pipeline and inject a target, i really don't want to have to start all of the other tasks that are triggered by new targets. E.g. I don't care about building the target with other instrumentations, starting other fuzzers, etc. At the moment this overhead is still manageable but it won't be for long.

**Comment by rhelmot** [comment]
`pd launch task job`?

**Comment by Lukas-Dresel** [comment]
I'd like to test, e.g. `target -> buildguy -> symcts -> asan_guy -> derive_path`, are you suggesting I just launch them all in order? there can be many though. I'd like to basically say "execute this subgraph" of the pipeline.

**Comment by rhelmot** [comment]
We support disabling individual tasks (not exposed by the current interfaces but it's there), are you okay with that?

**Comment by rhelmot** [comment]
fe19399dad13f957687f2a8e0dd657c987e4c65a
